In [ ]:
pwd


'/Users/abirhossain'

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
from pandas import *
 
# reading CSV file
colnames = ['score', 'title', 'Text']
df = read_csv("/content/drive/MyDrive/amazon - Sheet1.csv",names=colnames)
 
# converting column data to list



In [ ]:
!pip install openai

In [ ]:
pip install aiohttp

In [8]:
import openai
import pandas as pd
import numpy as np

# Set up your OpenAI API key
openai.api_key = "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"

# Load your dataset into a Pandas dataframe


# Define the prompt to use for GPT-3 embeddings
prompt = "Get embeddings for the following input: "
df=df[:10000]
# Initialize an empty list to store the embeddings
embeddings = []

# Loop over the rows in your dataset and generate embeddings for each one
for i, row in df.iterrows():
    input_text = row["Text"]
    resp = openai.Embedding.create(
    input=input_text,
    engine="text-similarity-davinci-001")
    embedding = resp['data'][0]['embedding']
    embeddings.append(embedding)

# Convert the list of embeddings to a numpy array
embedding_array = np.array(embeddings)

# Add the embeddings to a new column in your dataframe
df["embeddings"] = list(embedding_array)

# Save the updated dataframe to a new file


In [9]:
df

score                                              title  \
0         2                     Stuning even for the non-gamer   
1         2              The best soundtrack ever to anything.   
2         2                                           Amazing!   
3         2                               Excellent Soundtrack   
4         2  Remember, Pull Your Jaw Off The Floor After He...   
...     ...                                                ...   
9995      2  A revelation of life in small town America in ...   
9996      2   Great biography of a very interesting journalist   
9997      1             Interesting Subject; Poor Presentation   
9998      1                                          Don't buy   
9999      2                   Beautiful Pen and Fast Delivery.   

                                                   Text  \
0     This sound track was beautiful! It paints the ...   
1     I'm reading a lot of reviews saying that this ...   
2     This soundtrack is my favorite music of all ti...   
3     I truly like this soundtrack and I enjoy video...   
4     If you've played the game, you know how divine...   
...                                                 ...   
9995  Though a scholarly biography, the book reveals...   
9996  This biography of Arthur Aull, a small-town jo...   
9997  You'd be hard-pressed to tell a boring story a...   
9998  The box looked used and it is obviously not ne...   
9999  The pen was shipped promptly. This is the clas...   

                                             embeddings  
0     [-0.0051698824390769005, 0.009145737625658512,...  
1     [-0.010749110020697117, 0.014188317582011223, ...  
2     [-0.005023616831749678, 0.014521838165819645, ...  
3     [-0.0029200015123933554, 0.0017773234285414219...  
4     [-0.007275694981217384, 0.010098435916006565, ...  
...                                                 ...  
9995  [-0.0027548768557608128, 0.0136601272970438, -...  
9996  [-0.004806109704077244, 0.006786963436752558, ...  
9997  [-0.005340352188795805, 0.0025924809742718935,...  
9998  [-0.010483874939382076, 0.010826983489096165, ...  
9999  [-0.002176294568926096, 0.010070323012769222, ...  

[10000 rows x 4 columns]

In [ ]:
df = pd.read_csv("/content/your5.csv", sep=',', decimal=',')

In [ ]:
df

score                                              titie  \
0         3  Wall St. Bears Claw Back Into the Black (Reuters)   
1         3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2         3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3         3  Iraq Halts Oil Exports from Main Southern Pipe...   
4         3  Oil prices soar to all-time record, posing new...   
...     ...                                                ...   
9995      4  Winamp flaw: Digital attacks use skins for cam...   
9996      4                     BMC adds PeopleSoft management   
9997      3                    CAO chief faces Singapore probe   
9998      3              A Microsoft deal gets full EU inquiry   
9999      4                       Feds Bust File-Sharing Sites   

                                                   Text  \
0     Reuters - Short-sellers, Wall Street's dwindli...   
1     Reuters - Private investment firm Carlyle Grou...   
2     Reuters - Soaring crude prices plus worries\ab...   
3     Reuters - Authorities have halted oil export\f...   
4     AFP - Tearaway world oil prices, toppling reco...   
...                                                 ...   
9995  Users of the music player should watch out for...   
9996  BMC Software has released a new version of Pat...   
9997  The chief of Beijing-backed China Aviation Oil...   
9998  BRUSSELS The European Commission has opened an...   
9999  Operation Digital Gridlock targets peer-to-pee...   

                                             embeddings  
0     [-0.01314636506140232, 0.0075004142709076405, ...  
1     [-0.010748181492090225, 0.00025850709062069654...  
2     [-0.008965042419731617, -0.0005979867419227958...  
3     [-0.012323242612183094, 0.006488421931862831, ...  
4     [-0.011767380870878696, -0.0004722018493339419...  
...                                                 ...  
9995  [-0.013728415593504906, 0.005676782224327326, ...  
9996  [-0.00787639245390892, 0.005851670168340206, -...  
9997  [-0.009190421551465988, 0.010531350038945675, ...  
9998  [-0.013981848023831844, 0.00920925848186016, -...  
9999  [-0.013322371989488602, 0.010074407793581486, ...  

[10000 rows x 4 columns]

In [ ]:
df.to_csv("your6.csv",sep = ',')

In [ ]:
df

score                                              titie  \
0        3  Wall St. Bears Claw Back Into the Black (Reuters)   
1        3  Carlyle Looks Toward Commercial Aerospace (Reu...   
2        3    Oil and Economy Cloud Stocks' Outlook (Reuters)   
3        3  Iraq Halts Oil Exports from Main Southern Pipe...   
4        3  Oil prices soar to all-time record, posing new...   
..     ...                                                ...   
495      1  Seven Georgian soldiers wounded as South Osset...   
496      1               Rwandan Troops Arrive in Darfur (AP)   
497      1  Rwanda Troops Airlifted to Start AU Mission in...   
498      1    Bomb at India Independence Parade Kills 15 (AP)   
499      1  Australian FM to visit North Korea for talks o...   

                                                  Text  \
0    Reuters - Short-sellers, Wall Street's dwindli...   
1    Reuters - Private investment firm Carlyle Grou...   
2    Reuters - Soaring crude prices plus worries\ab...   
3    Reuters - Authorities have halted oil export\f...   
4    AFP - Tearaway world oil prices, toppling reco...   
..                                                 ...   
495  AFP - Sporadic gunfire and shelling took place...   
496  AP - Dozens of Rwandan soldiers flew into Suda...   
497  Reuters - Rwandan troops were airlifted on Sun...   
498  AP - A bomb exploded during an Independence Da...   
499  AFP - Australia's foreign minister will pay a ...   

                                            embeddings  
0    [-0.01314636506140232, 0.0075004142709076405, ...  
1    [-0.010748181492090225, 0.00025850709062069654...  
2    [-0.008965042419731617, -0.0005979867419227958...  
3    [-0.012323242612183094, 0.006488421931862831, ...  
4    [-0.011767380870878696, -0.0004722018493339419...  
..                                                 ...  
495  [-0.009578901343047619, 0.004194330424070358, ...  
496  [-0.0008159209974110126, 0.00434101652354002, ...  
497  [-0.006522478070110083, 0.004456075839698315, ...  
498  [-0.014149528928101063, 0.006523237098008394, ...  
499  [-0.009955797344446182, 0.0026821119245141745,...  

[500 rows x 4 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   score       500 non-null    int64 
 1   titie       500 non-null    object
 2   Text        500 non-null    object
 3   embeddings  500 non-null    object
dtypes: int64(1), object(3)
memory usage: 15.8+ KB


In [ ]:
a=["eating food", "I am hungry", "I am traveling" , "exploring new places"]

In [10]:
from sklearn.model_selection import train_test_split
 
X_train, X_test, y_train, y_test = train_test_split(
    list(df.embeddings.values),
    df.score,
    test_size = 0.2,
    random_state=42
)

In [11]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score
 
clf = RandomForestClassifier(n_estimators=100)
clf.fit(X_train, y_train)
preds = clf.predict(X_test)

In [ ]:
X_test

[array([-0.00924053, -0.00418236, -0.01196953, ...,  0.00208007,
         0.0091136 , -0.00302888]),
 array([-0.00145194,  0.00283576, -0.01386512, ..., -0.00071686,
         0.01018972, -0.0032033 ]),
 array([-0.00338411,  0.00804955, -0.01078348, ...,  0.0013289 ,
         0.02250575, -0.00101254]),
 array([-0.00896905,  0.00385022, -0.01194393, ..., -0.00209637,
         0.01211519, -0.01235623]),
 array([-0.01078822, -0.00129145, -0.01745396, ..., -0.00494064,
         0.01439698, -0.0133949 ]),
 array([-0.0118063 ,  0.00060258, -0.01445876, ..., -0.0098122 ,
         0.00862841, -0.00876768]),
 array([-1.08038429e-02,  4.89559025e-05, -1.87705681e-02, ...,
         1.27151754e-04,  1.01262275e-02,  2.33048899e-03]),
 array([-0.01518948, -0.00016907, -0.01281453, ..., -0.00271309,
         0.01034434, -0.01091585]),
 array([-0.0059302 , -0.00986887, -0.01339528, ...,  0.00184407,
         0.01372509, -0.00264005]),
 array([-0.00793306,  0.00634771, -0.02185237, ..., -0.0073877 ,
  

In [ ]:
preds

array([2, 2, 2, ..., 1, 1, 2])

In [12]:
print(classification_report(y_test,preds))

              precision    recall  f1-score   support

           1       0.95      0.96      0.95      1037
           2       0.96      0.94      0.95       963

    accuracy                           0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      0.95      0.95      2000

